name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./scs-invictus-landing # Add this line

      - name: Build project
        run: pnpm run build
        working-directory: ./scs-invictus-landing # Add this line

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scs-invictus-landing/dist # Update this line
          # cname: your-custom-domain.com # Uncomment and replace with your custom domain if you have one
